"""Initial migration.

Revision ID: 843b6c632237
Revises: 
Create Date: 2021-05-06 14:26:21.289317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843b6c632237'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=True),
    sa.Column('job_company', sa.String(length=50), nullable=True),
    sa.Column('job_date', sa.String(length=50), nullable=True),
    sa.Column('job_content', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience')
    # ### end Alembic commands ###
